name: Release
on:
  push:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build remapSlimJar --no-daemon --stacktrace
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.version }}
      - name: Write changelog to file
        run: echo "${{ steps.changelog_reader.outputs.changes }}" > build/tmp/CHANGELOG.md
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body_path: build/tmp/CHANGELOG.md
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create CurseForge release
        run: ./gradlew curseforge --no-daemon --stacktrace
        env:
          CURSE_API_TOKEN: ${{ secrets.CURSE_API_TOKEN }}
      - name: Create Modrinth release
        run: ./gradlew publishModrinth --no-daemon --stacktrace
        env:
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
